// tsup.config.ts
import { defineConfig } from "tsup";

const isWatch = process.argv.includes("--watch");

export default defineConfig({
  entry: {
    index: "src/index.ts",
    markdown: "src/markdown.ts",
  },
  format: ["cjs", "esm"],
  dts: true,
  splitting: false,
  sourcemap: true,
  clean: false, // keep dist/index.css alive across builds — generated by onSuccess below
  minify: false,
  loader: {
    ".svg": "dataurl",
  },
  external: [
    "@cjlapao/ui-kit",
    "react",
    "react-dom",
    "react-router-dom",
    "@uiw/react-md-editor",
    "react-markdown",
    "remark-gfm",
    "vfile",
  ],
  // Tailwind v4 postcss plugin only emits a small shim (~1KB) — we rely
  // on the CLI to generate the full 2MB bundle. Run this after tsup finishes
  // the JS builds.
  onSuccess: isWatch
    ? "npx @tailwindcss/cli -i ./src/styles.css -o ./dist/index.css && yalc push"
    : "npx @tailwindcss/cli -i ./src/styles.css -o ./dist/index.css",
});