// AUTO-GENERATED by vue/scripts/generate-vue-icons.ts — do not edit manually.
// Source: react/src/icons/components/ChevronRight.tsx
import { defineComponent, h } from "vue";

export const ChevronRight = defineComponent({
  name: "ChevronRight",
  setup() {
    return () =>
      h("svg", {
        "viewBox": "0 0 20 20",
        "fill": "none",
        "version": "1.1",
        "id": "svg1",
        "xmlns": "http://www.w3.org/2000/svg",
        innerHTML: "<path d=\"m 7,3 a 1,1 0 0 0 -0.7070313,0.2929688 1,1 0 0 0 0,1.4140624 L 11.585938,10 6.2929687,15.292969 a 1,1 0 0 0 0,1.414062 1,1 0 0 0 1.4140625,0 l 5.9999998,-6 a 1.0001,1.0001 0 0 0 0,-1.4140622 l -5.9999998,-6 A 1,1 0 0 0 7,3 Z\" fill=\"currentColor\" />",
      });
  },
});
