// AUTO-GENERATED by vue/scripts/generate-vue-icons.ts — do not edit manually.
// Source: react/src/icons/components/Drag.tsx
import { defineComponent, h } from "vue";

export const Drag = defineComponent({
  name: "Drag",
  setup() {
    return () =>
      h("svg", {
        "viewBox": "0 0 20 20",
        "fill": "currentColor",
        "xmlns": "http://www.w3.org/2000/svg",
        innerHTML: "<circle cx=\"6\" cy=\"5\" r=\"1.1\" /><circle cx=\"6\" cy=\"10\" r=\"1.1\" /><circle cx=\"6\" cy=\"15\" r=\"1.1\" /><circle cx=\"12\" cy=\"5\" r=\"1.1\" /><circle cx=\"12\" cy=\"10\" r=\"1.1\" /><circle cx=\"12\" cy=\"15\" r=\"1.1\" />",
      });
  },
});
