// AUTO-GENERATED by vue/scripts/generate-vue-icons.ts — do not edit manually.
// Source: react/src/icons/components/Equal.tsx
import { defineComponent, h } from "vue";

export const Equal = defineComponent({
  name: "Equal",
  setup() {
    return () =>
      h("svg", {
        "viewBox": "0 0 24 24",
        "fill": "none",
        "version": "1.1",
        "id": "svg2",
        "xmlns": "http://www.w3.org/2000/svg",
        innerHTML: "<path fill=\"currentColor\" d=\"m 9,9 a 1,1 0 0 0 -1,1 1,1 0 0 0 1,1 h 6 a 1,1 0 0 0 1,-1 1,1 0 0 0 -1,-1 z\" /><path fill=\"currentColor\" d=\"m 9,13 a 1,1 0 0 0 -1,1 1,1 0 0 0 1,1 h 6 a 1,1 0 0 0 1,-1 1,1 0 0 0 -1,-1 z\" />",
      });
  },
});
