// AUTO-GENERATED by vue/scripts/generate-vue-icons.ts — do not edit manually.
// Source: react/src/icons/components/ThemeAuto.tsx
import { defineComponent, h } from "vue";

export const ThemeAuto = defineComponent({
  name: "ThemeAuto",
  setup() {
    return () =>
      h("svg", {
        "focusable": "false",
        "aria-hidden": "true",
        "viewBox": "0 0 24 24",
        innerHTML: "<path fill=\"currentColor\" d=\"M10.85 12.65h2.3L12 9zM20 8.69V4h-4.69L12 .69 8.69 4H4v4.69L.69 12 4 15.31V20h4.69L12 23.31 15.31 20H20v-4.69L23.31 12zM14.3 16l-.7-2h-3.2l-.7 2H7.8L11 7h2l3.2 9z\" ></path>",
      });
  },
});
